[package]
name = "from-bytes-test"
version = "0.1.0"
edition = "2021"

[dependencies]
from-bytes-macro = { path = "../from-bytes-macro" }
quote = "1.0.38"
syn = {  version = "2.0.95" , features = ["extra-traits"] }
